### ISSUE TITLE
How to run your project?

### ISSUE THREAD

**Issue by dragen1860** [yaoling1997/Transitioning360#1]
Dear author:
  THanks for sharing this project. As a newbiee in this domain, i felt confused about how to get started from your work. Could you kindly illustrate how to run this? thanks again.

**Comment by yaoling1997** [comment]
Sure, we added the video tutorial to demonstate how to run this Transitioning360 player, you can refer to [How To Run Transitioning360 Player](https://www.youtube.com/watch?v=CfEacIJVZIw) for more details.
